import { ParamGroup, ParamName, ParamPatchType } from "./enum"
import { ParamData } from "./interface"
export const paramList:{ [paramName: string]: ParamData }={}

paramList[ParamName.legacy_layout]={
    name:ParamName.legacy_layout,
    group:ParamGroup.LAYOUT,
    toggle:{
        label:"legacy_layout",
        defaultEnable:[false,false,false,false,false],
    },
    patch:[]
}
paramList[ParamName.width]={
    name:ParamName.width,
    group:ParamGroup.LAYOUT,
    preCondition:[{disable:[ParamName.fps_only]}],
    toggle:{
        label:"width",
        defaultEnable:[false,false,false,false,false],
    },
    patch:[{
        label:"width",
        description:"width",
        type:ParamPatchType.slider,
        args:[1,2160,1,true],
        defaultValue:[800,800,800,800,800],
    }]
}
paramList[ParamName.position]={
    name:ParamName.position,
    group:ParamGroup.LAYOUT,
    toggle:{
        label:"position",
        defaultEnable:[false,false,false,false,false],
    },
    patch:[
        {
            label:"position",
            type:ParamPatchType.dropdown,
            args:["top-left","top-right","middle-left","middle-right","bottom-left","bottom-right","top-center","bottom_center"],
            defaultValue:["top-left","top-left","top-left","top-left","top-left"],
        }
    ]
}
paramList[ParamName.offset_x]={
    name:ParamName.offset_x,
    group:ParamGroup.LAYOUT,
    toggle:{
        label:"offset_x",
        defaultEnable:[false,false,false,false,false],
    },
    patch:[{
        label:"offset_x",
        description:"offset_x",
        type:ParamPatchType.slider,
        args:[0,2160,1,true],
        defaultValue:[0,0,0,0,0],
    }]
}
paramList[ParamName.offset_y]={
    name:ParamName.offset_y,
    group:ParamGroup.LAYOUT,
    toggle:{
        label:"offset_y",
        defaultEnable:[false,false,false,false,false],
    },
    patch:[{
        label:"offset_y",
        description:"offset_y",
        type:ParamPatchType.slider,
        args:[0,2160,1,true],
        defaultValue:[0,0,0,0,0],
    }]
}
paramList[ParamName.alpha]={
    name:ParamName.alpha,
    group:ParamGroup.SETTING,
    toggle:{
        label:"alpha",
        description:"alpha",
        defaultEnable:[false,false,false,false,false],
    },
    patch:[{
        label:"alpha",
        description:"alpha",
        type:ParamPatchType.slider,
        args:[0,1,0.01,false],
        defaultValue:[0.8,0.8,0.8,0.8,0.8],
    }]
}
paramList[ParamName.background_alpha]={
    name:ParamName.background_alpha,
    group:ParamGroup.SETTING,
    toggle:{
        label:"background_alpha",
        description:"background_alpha",
        defaultEnable:[false,false,false,false,false],
    },
    patch:[{
        label:"background_alpha",
        description:"background_alpha",
        type:ParamPatchType.slider,
        args:[0,1,0.01],
        defaultValue:[0.8,0.8,0.8,0.8,0.8],
    }]
}
paramList[ParamName.cpu_stats]={
    name:ParamName.cpu_stats,
    group:ParamGroup.CPU,
    preCondition:[{disable:[ParamName.legacy_layout,ParamName.fps_only]}],
    toggle:{
        label:"cpu_stats",
        defaultEnable:[false,false,false,false,false],
    },
    patch:[]
}
paramList[ParamName.cpu_text]={
    name:ParamName.cpu_text,
    group:ParamGroup.CPU,
    preCondition:[{enable:[ParamName.cpu_stats],disable:[ParamName.legacy_layout]},
                {enable:[ParamName.legacy_layout]}],
    toggle:{
        label:"cpu_text",
        defaultEnable:[false,false,false,false,false],
    },
    patch:[{
        label:"cpu_text",
        description:"cpu_text",
        type:ParamPatchType.textInput,
        args:[false],
        defaultValue:["CPU","CPU","CPU","CPU","CPU"],
    }]
}
paramList[ParamName.cpu_load_change]={
    name:ParamName.cpu_load_change,
    group:ParamGroup.CPU,
    preCondition:[{enable:[ParamName.cpu_stats],disable:[ParamName.legacy_layout]},
                {enable:[ParamName.legacy_layout]}],
    toggle:{
        label:"cpu_load_change",
        defaultEnable:[false,false,false,false,false],
    },
    patch:[]
}
paramList[ParamName.core_load]={
    name:ParamName.core_load,
    group:ParamGroup.CPU,
    preCondition:[{enable:[ParamName.cpu_stats],disable:[ParamName.legacy_layout]},
                {enable:[ParamName.legacy_layout]}],
    toggle:{
        label:"core_load",
        defaultEnable:[false,false,false,false,false],
    },
    patch:[]
}
paramList[ParamName.core_load_change]={
    name:ParamName.core_load_change,
    group:ParamGroup.CPU,
    preCondition:[{enable:[ParamName.core_load]}],
    toggle:{
        label:"core_load_change",
        defaultEnable:[false,false,false,false,false],
    },
    patch:[]
}
paramList[ParamName.cpu_mhz]={
    name:ParamName.cpu_mhz,
    group:ParamGroup.CPU,
    preCondition:[{enable:[ParamName.cpu_stats],disable:[ParamName.legacy_layout]},
                {enable:[ParamName.legacy_layout]}],
    toggle:{
        label:"cpu_mhz",
        defaultEnable:[false,false,false,false,false],
    },
    patch:[]
}
paramList[ParamName.cpu_power]={
    name:ParamName.cpu_power,
    group:ParamGroup.CPU,
    preCondition:[{enable:[ParamName.cpu_stats],disable:[ParamName.legacy_layout]},
                {enable:[ParamName.legacy_layout]}],
    toggle:{
        label:"cpu_power",
        defaultEnable:[false,false,false,false,false],
    },
    patch:[]
}
paramList[ParamName.cpu_temp]={
    name:ParamName.cpu_temp,
    group:ParamGroup.CPU,
    preCondition:[{enable:[ParamName.cpu_stats],disable:[ParamName.legacy_layout]},
                {enable:[ParamName.legacy_layout]}],
    toggle:{
        label:"cpu_temp",
        defaultEnable:[false,false,false,false,false],
    },
    patch:[]
}

paramList[ParamName.gpu_stats]={
    name:ParamName.gpu_stats,
    group:ParamGroup.GPU,
    preCondition:[{disable:[ParamName.legacy_layout,ParamName.fps_only]}],
    toggle:{
        label:"gpu_stats",
        defaultEnable:[false,false,false,false,false],
    },
    patch:[]
}
paramList[ParamName.gpu_text]={
    name:ParamName.gpu_text,
    group:ParamGroup.GPU,
    preCondition:[{enable:[ParamName.gpu_stats],disable:[ParamName.legacy_layout]},
                {enable:[ParamName.legacy_layout]}],
    toggle:{
        label:"gpu_text",
        defaultEnable:[false,false,false,false,false],
    },
    patch:[{
        label:"gpu_text",
        description:"gpu_text",
        type:ParamPatchType.textInput,
        args:[false],
        defaultValue:["GPU","GPU","GPU","GPU","GPU"],
    }]
}
paramList[ParamName.gpu_load_change]={
    name:ParamName.gpu_load_change,
    group:ParamGroup.GPU,
    preCondition:[{enable:[ParamName.gpu_stats],disable:[ParamName.legacy_layout]},
                {enable:[ParamName.legacy_layout]}],
    toggle:{
        label:"gpu_load_change",
        defaultEnable:[false,false,false,false,false],
    },
    patch:[]
}
paramList[ParamName.gpu_core_clock]={
    name:ParamName.gpu_core_clock,
    group:ParamGroup.GPU,
    preCondition:[{enable:[ParamName.gpu_stats],disable:[ParamName.legacy_layout]},
                {enable:[ParamName.legacy_layout]}],
    toggle:{
        label:"gpu_core_clock",
        defaultEnable:[false,false,false,false,false],
    },
    patch:[]
}
paramList[ParamName.gpu_power]={
    name:ParamName.gpu_power,
    group:ParamGroup.GPU,
    preCondition:[{enable:[ParamName.gpu_stats],disable:[ParamName.legacy_layout]},
                {enable:[ParamName.legacy_layout]}],
    toggle:{
        label:"gpu_power",
        defaultEnable:[false,false,false,false,false],
    },
    patch:[]
}
paramList[ParamName.gpu_temp]={
    name:ParamName.gpu_temp,
    group:ParamGroup.GPU,
    preCondition:[{enable:[ParamName.gpu_stats],disable:[ParamName.legacy_layout]},
                {enable:[ParamName.legacy_layout]}],
    toggle:{
        label:"gpu_temp",
        defaultEnable:[false,false,false,false,false],
    },
    patch:[]
}
paramList[ParamName.vram]={
    name:ParamName.vram,
    group:ParamGroup.RAM,
    preCondition:[{disable:[ParamName.fps_only]}],
    toggle:{
        label:"vram",
        defaultEnable:[false,false,false,false,false],
    },
    patch:[]
}
paramList[ParamName.ram]={
    name:ParamName.ram,
    group:ParamGroup.RAM,
    preCondition:[{disable:[ParamName.fps_only]}],
    toggle:{
        label:"ram",
        defaultEnable:[false,false,false,false,false],
    },
    patch:[]
}
paramList[ParamName.swap]={
    name:ParamName.swap,
    group:ParamGroup.RAM,
    preCondition:[{disable:[ParamName.fps_only]}],
    toggle:{
        label:"swap",
        defaultEnable:[false,false,false,false,false],
    },
    patch:[]
}
paramList[ParamName.battery]={
    name:ParamName.battery,
    group:ParamGroup.BATT,
    preCondition:[{disable:[ParamName.fps_only]}],
    toggle:{
        label:"battery",
        description:"battary",
        defaultEnable:[false,false,true,true,true],
    },
    patch:[]
}
paramList[ParamName.battery_icon]={
    name:ParamName.battery_icon,
    group:ParamGroup.BATT,
    preCondition:[{enable:[ParamName.battery]}],
    toggle:{
        label:"battery_icon",
        defaultEnable:[false,false,false,false,false],
    },
    patch:[]
}
paramList[ParamName.fan]={
    name:ParamName.fan,
    group:ParamGroup.OTHER,
    preCondition:[{disable:[ParamName.fps_only]}],
    toggle:{
        label:"fsr",
        defaultEnable:[false,false,false,false,false],
    },
    patch:[]
}
paramList[ParamName.fsr]={
    name:ParamName.fsr,
    group:ParamGroup.OTHER,
    preCondition:[{disable:[ParamName.fps_only]}],
    toggle:{
        label:"fan",
        defaultEnable:[false,false,false,false,false],
    },
    patch:[]
}
paramList[ParamName.fps]={
    name:ParamName.fps,
    group:ParamGroup.OTHER,
    preCondition:[{disable:[ParamName.legacy_layout]}],
    toggle:{
        label:"fps",
        defaultEnable:[false,false,false,false,false],
    },
    patch:[]
}
paramList[ParamName.fps_only]={
    name:ParamName.fps_only,
    group:ParamGroup.OTHER,
    preCondition:[],
    toggle:{
        label:"fps_only",
        defaultEnable:[false,false,false,false,false],
    },
    patch:[]
}
paramList[ParamName.frame_timing]={
    name:ParamName.frame_timing,
    group:ParamGroup.OTHER,
    preCondition:[{disable:[ParamName.legacy_layout,ParamName.fps_only]}],
    toggle:{
        label:"frame_timing",
        defaultEnable:[false,false,false,false,false],
    },
    patch:[]
}